services:
  app:
    image: analyticsapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: Dockerfile
    #     - action: rebuild
    #       path: requirements.txt
    #     - action: rebuild
    #       path: compose.yaml
    volumes:
      - ./src:/code:rw